/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domain.Nastavnik;
import domain.Zvanje;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vojislav
 */
public class FrmDetalji extends javax.swing.JFrame {

    /**
     * Creates new form FrmDetalji
     */
    public FrmDetalji() {
        initComponents();
    }
    Nastavnik selektovaniNastavnik;
    FrmDetalji(Nastavnik selektovaniNastavnik) {
        this.selektovaniNastavnik = selektovaniNastavnik;
        
        initComponents();
        btnSacuvaj.setVisible(false);
        txtIme.setText(selektovaniNastavnik.getIme());
        txtPrezime.setText(selektovaniNastavnik.getPrezime());
        cbZvanje.setModel(new DefaultComboBoxModel<>(Zvanje.values()));
        cbZvanje.setSelectedItem(selektovaniNastavnik.getZvanje());
        txtIme.setEditable(false);
        txtPrezime.setEditable(false);
        cbZvanje.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbZvanje = new javax.swing.JComboBox<>();
        btnObrisi = new javax.swing.JButton();
        btnIzmena = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Zvanje");

        cbZvanje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmena.setText("Omoguci izmenu");
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIme)
                                    .addComponent(txtPrezime)
                                    .addComponent(cbZvanje, 0, 251, Short.MAX_VALUE)))
                            .addComponent(btnIzmena, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnObrisi)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite trajno obrisati nastavnika iz sistema?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            boolean deleted = obrisiProfesoraIzBaze(); 
            if (deleted) {
                JOptionPane.showMessageDialog(this, "Nastavnik uspešno obrisan iz sistema.");
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Brisanje nije uspelo. Molimo pokušajte ponovo.");
            }
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed
         
            txtIme.setEditable(true);
            txtPrezime.setEditable(true);
            btnSacuvaj.setVisible(true);

    }//GEN-LAST:event_btnIzmenaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        Connection connection = null;
        String url = "jdbc:mysql://localhost:3306/projsoft";
        String user = "root";
        String pass = "";
        try {
            connection = DriverManager.getConnection(url,user,pass);
            String upit = "UPDATE nastavnik SET ime = ?, prezime = ?, zvanje_id = ? WHERE id = ?";
            PreparedStatement statement = connection.prepareStatement(upit);
            statement.setString(1, txtIme.getText());
            statement.setString(2, txtPrezime.getText());
            selektovaniNastavnik.setZvanje(Zvanje.valueOf(cbZvanje.getSelectedIndex()+1));
            statement.setInt(3, selektovaniNastavnik.getZvanje().getZvanjeId());
            statement.setInt(4, selektovaniNastavnik.getId());
            int redovi = statement.executeUpdate();
            System.out.println("Uspesno apdejtovano redova: "+redovi);
            statement.close();
            connection.close();
            this.dispose();
           
        } catch (SQLException ex) {
            Logger.getLogger(FrmDetalji.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmena;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cbZvanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private boolean obrisiProfesoraIzBaze() {
        Connection connection = null;
        String url = "jdbc:mysql://localhost:3306/projsoft";
        String user = "root";
        String pass = "";
        try {
            connection = DriverManager.getConnection(url,user,pass);
            String upit = "delete from nastavnik where id=?";
            PreparedStatement statement = connection.prepareStatement(upit);
            statement.setInt(1, selektovaniNastavnik.getId());
            statement.executeUpdate();
            statement.close();
            connection.close();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FrmDetalji.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        return true;
    }
}
